version: '3.8'
services:
  web:
    build: .
    ports:
      - 44341:80
    environment:
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1433:1433"
    restart: always
    environment:
      SA_PASSWORD: "Pass@ord"
      ACCEPT_EULA: "Y"