version: '3.9'
services:
  web:
    build: .
    ports:
      - 44341:44341
    environment:
      - ASPNETCORE_URLS=http://*:44341
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1489:1433"
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"