FROM mcr.microsoft.com/dotnet/aspnet:3.1-focal AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1-focal AS build
WORKDIR /src
COPY ["Mediator.csproj", "./"]
RUN dotnet restore "Mediator.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Mediator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mediator.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mediator.dll"]
